//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLibrary.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.MovementType = new HashSet<MovementType>();
        }
    
        public int bookId { get; set; }
        public string bookName { get; set; }
        public Nullable<byte> categoryId { get; set; }
        public Nullable<int> authorId { get; set; }
        public string publicationYear { get; set; }
        public string publishingHouse { get; set; }
        public string pageNumber { get; set; }
        public Nullable<bool> statusBook { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovementType> MovementType { get; set; }
    }
}
