//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLibrary.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashRegisters
    {
        public int id { get; set; }
        public string monthDate { get; set; }
        public Nullable<decimal> totalAmount { get; set; }
    }
}
