//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLibrary.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penalties
    {
        public int penaltyId { get; set; }
        public Nullable<int> memberId { get; set; }
        public Nullable<int> movementTypeId { get; set; }
        public Nullable<System.DateTime> penaltyStart { get; set; }
        public Nullable<System.DateTime> penaltyEnd { get; set; }
        public Nullable<decimal> money { get; set; }
    
        public virtual Members Members { get; set; }
        public virtual MovementType MovementType { get; set; }
    }
}
